### ISSUE TITLE
sqlite error with linux-arm

### ISSUE THREAD

**Issue by liam8888999** [jasongdove/ErsatzTV#311] opened 2021-07-14 05:23 UTC
when running on a raspberry pi it returns the error:

Unhandled exception. System.DllNotFoundException: Unable to load shared library 'SQLite.Interop.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSQLite.Interop.dll: cannot open shared object file: No such file or directory
   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
   at System.Data.SQLite.SQLite3.StaticIsInitialized()
   at System.Data.SQLite.SQLiteLog.Initialize(String className)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at Serilog.Sinks.SQLite.SQLiteSink.GetSqLiteConnection()
   at Serilog.Sinks.SQLite.SQLiteSink.InitializeDatabase()
   at Serilog.Sinks.SQLite.SQLiteSink..ctor(String sqlLiteDbPath, String tableName, IFormatProvider formatProvider, Boolean storeTimestampInUtc, Nullable`1 retentionPeriod, Nullable`1 retentionCheckInterval, UInt32 batchSize, UInt32 maxDatabaseSize, Boolean rollOver)
   at Serilog.LoggerConfigurationSQLiteExtensions.SQLite(LoggerSinkConfiguration loggerConfiguration, String sqliteDbPath, String tableName, LogEventLevel restrictedToMinimumLevel, IFormatProvider formatProvider, Boolean storeTimestampInUtc, Nullable`1 retentionPeriod, Nullable`1 retentionCheckInterval, LoggingLevelSwitch levelSwitch, UInt32 batchSize, UInt32 maxDatabaseSize, Boolean rollOver)
   at ErsatzTV.Program.Main(String[] args) in /home/runner/work/ErsatzTV/ErsatzTV/ErsatzTV/Program.cs:line 25
   at ErsatzTV.Program.<Main>(String[] args)
Aborted

**Comment by liam8888999** [comment] 2021-07-14 05:45
from the little bit of research I did it appears the build target could be wrong and should possibly be: armv7-unknown-linux-gnueabihf

**Comment by jasongdove** [comment] 2021-07-14 10:38
I'll dig up a Pi and do some local testing.

**Comment by jasongdove** [comment] 2021-07-15 02:34
This is caused by an incompatibility with the sqlite log sink https://github.com/saleem-mirza/serilog-sinks-sqlite

I will have to find a replacement log sink that also supports `linux-arm`.

**Comment by jasongdove** [comment] 2021-07-15 12:07
I think this will be fixed with release 51. For now, please try copying [these files](https://github.com/jasongdove/ErsatzTV/tree/main/lib/linux-arm) into the directory with the `ErsatzTV` binary.

**Comment by thorsforge** [comment] 2021-07-17 10:40
Not the OP, but I came here with the same error he posted and copying those 2 files lets the server start up! so thank you for the quick fix!

**Comment by liam8888999** [comment] 2021-07-17 13:59
> Not the OP, but I came here with the same error he posted and copying those 2 files lets the server start up! so thank you for the quick fix!

yes. hopefully this can be included in the next release

**Comment by jasongdove** [comment] 2021-07-18 12:24
Release [v0.0.51-alpha](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.0.51-alpha) contains the appropriate interop files in the `linux-arm` archive.

**Closed by jasongdove** 2021-07-18 12:24 UTC
Labels: bug
