### ISSUE TITLE
Feature Request: Subtitles

### ISSUE THREAD

**Issue by RW456** [jasongdove/ErsatzTV#204] opened 2021-05-23 22:21 UTC
I used this to make an anime channel. With anime, you kind of need subtitles, as the audio is in japanese. Can you add some way to add subtitles to these streams? You could do it with an ffmpeg flag i think. Thanks in advance

**Comment by jasongdove** [comment] 2021-05-23 23:05
Thanks for the feedback. This is definitely on the roadmap.

Closing as a duplicate of #45

**Closed by jasongdove** 2021-05-23 23:05 UTC
Labels: duplicate
