### ISSUE TITLE
Arm image

### ISSUE THREAD

**Issue by brianhenson** [jasongdove/ErsatzTV#482] opened 2021-11-15 04:28 UTC
Good Afternoon, 

I love your software and I would love to have an arm image for it on dockerhub. I saw you were talking about it on a previous issue but I dont see any images on the hub. Can we get a prebuilt by chance?

**Comment by jasongdove** [comment] 2021-11-16 16:32
Will investigate if this is possible. Which hardware are you looking to run on?

**Comment by brianhenson** [comment] 2021-11-16 18:35
I am running it on 32bit raspbian but would love to run it on the 64bit version (speed boost) but it fails to start on the 64bit version.

**Comment by vrisalab** [comment] 2021-12-30 17:51
I second this, I want to run this on a rock pi with a 64 bit OS

**Comment by jasongdove** [comment] 2022-01-04 01:00
The issue is with the [current ffmpeg base docker image](https://github.com/jrottenberg/ffmpeg) which isn't published for and doesn't build against arm64. FFmpeg is pretty essential, but I will investigate alternative base images.

**Comment by jasongdove** [comment] 2022-01-31 14:33
So it's not a docker image yet, but I added `linux-arm64` to the build matrix and you can try the binaries from the [latest develop release](https://github.com/jasongdove/ErsatzTV/releases/tag/develop).

**Comment by jasongdove** [comment] 2022-05-03 10:28
I just created a new docker tag `develop-arm64`. I have tested `HLS Direct` successfully, but my only arm64 system isn't powerful enough to do any transcoding. Would be very helpful to have someone test and report back.

**Comment by rickmills** [comment] 2022-07-01 10:06
Is this something thats likely to work on a Pi 4? If so I'll give it a try :)

**Comment by jasongdove** [comment] 2022-07-01 13:10
> Is this something thats likely to work on a Pi 4? If so I'll give it a try :) I've got an 8gb model recently decomissioned so might be a good test bed.

There are now two tag suffixes, `-arm` and `-arm64` depending on your architecture. Someone in Discord has had limited success transcoding low resolution content on a pi, but I would be surprised if anything other than `HLS Direct` streaming mode works reliably.

**Comment by jasongdove** [comment] 2022-07-31 15:24
Closing this as arm docker images now exist. Please open a new issue if you encounter any problems with the images.

**Closed by jasongdove** 2022-07-31 15:24 UTC
Labels: enhancement
